#!/bin/bash
# Annotate an i3 workspace with a Font Awesome icon

DMENU_OPTS=(-b -fn "Droid Sans Mono-14:normal" -sf \#ebdbb2 -sb \#d79921 -nf \#ebdbb2 -nb \#282828)
CWD=$(dirname "$0")
FA="$CWD/fa"

# Look up icon
match_str=$(cat "$FA" | dmenu "${DMENU_OPTS[@]}")
match_icon=$(echo "$match_str" | cut -d\  -f2)

if [[ "$match_str" == "$match_icon" ]]; then
    # Fallback to string input if icon was not found
    match_icon="$match_str"
fi

# i3 integration
# Thanks to https://stackoverflow.com/a/24225599
i3_ws_id=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).num')

# Prepend id to workspaces 4+
if [[ -z "$match_str" ]]; then
    i3_ws_name="$i3_ws_id"
elif [[ "$i3_ws_id" -gt 3 ]]; then
    i3_ws_name="$i3_ws_id:${i3_ws_id} $match_icon"
else
    i3_ws_name="$i3_ws_id:$match_icon"
fi

i3-msg -q "rename workspace to $i3_ws_name"
